# Generated by Django 4.0.3 on 2022-04-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='ip_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
