# Generated by Django 4.0.3 on 2022-03-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0002_remove_warehouse_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='features',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agregator.features'),
            preserve_default=False,
        ),
    ]
