# Generated by Django 4.0.3 on 2022-04-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0003_warehouse_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_class',
            field=models.CharField(choices=[('No value', 'Не задано'), ('Sharing', 'Склад от компании'), ('3pl', '3pl-оператор'), ('Storage_only_wh', 'Склад ответственного хранения')], default='No value', max_length=100),
        ),
    ]
