# Generated by Django 4.0.3 on 2022-04-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0004_alter_warehouse_warehouse_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='long_term_commitment',
            field=models.BooleanField(default=False),
        ),
    ]
