# Generated by Django 4.0.3 on 2022-04-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0007_remove_storagecond_floor_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='food',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
