# Generated by Django 4.0.3 on 2022-04-21 00:20

import agregator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0010_application_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=agregator.models.upload_path)),
            ],
            options={
                'verbose_name': 'Фото склада',
                'verbose_name_plural': 'Фото склада',
            },
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='image',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agregator.images'),
        ),
    ]
