# Generated by Django 4.0.3 on 2022-04-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0011_images_remove_warehouse_image_warehouse_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agregator.images'),
        ),
    ]
