# Generated by Django 4.0.3 on 2022-04-21 00:53

import agregator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0013_warehouseimages_remove_warehouse_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='image',
            field=models.FileField(blank=True, upload_to=agregator.models.upload_path),
        ),
    ]
