# Generated by Django 4.0.3 on 2022-04-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0014_alter_warehouse_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseimages',
            old_name='post',
            new_name='warehouse',
        ),
    ]
