# Generated by Django 4.0.3 on 2022-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0016_alter_warehouse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='dangerous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='pharmacy',
            field=models.BooleanField(default=False),
        ),
    ]
