# Generated by Django 4.0.3 on 2022-05-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0017_alter_features_alcohol_alter_features_dangerous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='condition',
            field=models.CharField(choices=[('No value', 'Не задано'), ('Heated', 'Отапливаемый'), ('Warmed', 'Утепленный'), ('Non-heated', 'Неотапливаемый'), ('Freezer-WH', 'Морозильный'), ('Cold-WH', 'Холодильный')], default='No value', max_length=32),
        ),
    ]
