# Generated by Django 4.0.3 on 2022-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0018_alter_features_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='condition',
            field=models.CharField(choices=[('No value', 'Не задано'), ('Regulated', 'Регулируемый температурный режим'), ('Heated', 'Отапливаемый'), ('Warmed', 'Утепленный'), ('Non-heated', 'Неотапливаемый'), ('Freezer-WH', 'Морозильный'), ('Cold-WH', 'Холодильный')], default='No value', max_length=32),
        ),
    ]
