# Generated by Django 4.0.3 on 2022-05-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0019_alter_features_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghours',
            old_name='teekday',
            new_name='weekday',
        ),
    ]
