# Generated by Django 4.0.3 on 2022-05-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0023_alter_surveyresults_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresults',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
