# Generated by Django 4.0.3 on 2022-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0024_alter_surveyresults_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresults',
            name='warehouse_class',
            field=models.CharField(choices=[('No value', 'Не задано'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C')], default='No value', max_length=100),
        ),
    ]
