# Generated by Django 4.0.3 on 2022-06-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0025_alter_surveyresults_warehouse_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagecond',
            name='max_storage_height',
            field=models.FloatField(),
        ),
    ]
