# Generated by Django 4.0.3 on 2022-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0026_alter_storagecond_max_storage_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='parking_cost',
            field=models.IntegerField(verbose_name='Стоимость парковки'),
        ),
    ]
