# Generated by Django 4.0.3 on 2022-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0027_alter_logistics_parking_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='parking_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость парковки'),
        ),
    ]
