# Generated by Django 4.0.3 on 2022-06-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0029_rename_wh_lon_warehouse_wh_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='timefrom',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='timeto',
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
    ]
