# Generated by Django 4.0.3 on 2022-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0030_alter_workinghours_timefrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, null=True),
        ),
    ]
