# Generated by Django 4.0.3 on 2022-06-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0031_alter_workinghours_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghours',
            old_name='timefrom',
            new_name='time_from',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='timeto',
            new_name='time_to',
        ),
    ]
