# Generated by Django 4.0.3 on 2022-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0032_rename_timefrom_workinghours_time_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='time_to',
        ),
        migrations.AddField(
            model_name='workinghours',
            name='timeto',
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
    ]
