# Generated by Django 4.0.3 on 2022-06-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0033_remove_workinghours_time_to_workinghours_timeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghours',
            old_name='timeto',
            new_name='time_to',
        ),
    ]
