# Generated by Django 4.0.3 on 2022-06-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0037_workinghours_break_flag_workinghours_break_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=5, null=True, verbose_name='До какого дня недели'),
        ),
    ]
