# Generated by Django 4.0.3 on 2022-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0039_alter_storagecond_pallet_storage_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagecond',
            name='pallet_storage_capacity',
            field=models.IntegerField(choices=[('No value', 'Не задано'), ('<50', 'Меньше 50'), ('50-250', '50-250'), ('250-500', '250-500'), ('500-1000', '500-1000'), ('1000+', 'больше 1000')], default='No value', verbose_name='Вместимость (палет)'),
        ),
    ]
