# Generated by Django 4.0.3 on 2022-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0042_alter_workinghours_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
