# Generated by Django 4.0.3 on 2022-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0043_alter_warehouse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecond',
            name='bulky_cargo_storage',
            field=models.BooleanField(default=False, verbose_name='Возможность хранения крупногабаритного груза'),
        ),
    ]
