# Generated by Django 4.0.3 on 2022-06-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0044_storagecond_bulky_cargo_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='domestic_premises',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие бытовых помещений'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='office_premises',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие офисных помещений'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='office_premises_square',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Размер офисных помещений (м2)'),
        ),
    ]
