# Generated by Django 4.0.3 on 2022-06-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0046_alter_warehouse_office_premises_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='time_from',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время начала работы (09:00 = 900)'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='time_to',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время окончания работы (если 24 часа, то значение поля - 2400)'),
        ),
    ]
