# Generated by Django 4.0.3 on 2022-06-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0047_alter_workinghours_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='wh_latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='wh_longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
    ]
