# Generated by Django 4.0.3 on 2022-06-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0048_alter_warehouse_wh_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
