# Generated by Django 4.0.3 on 2022-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0049_alter_warehouse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='friday_time_from',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время начала работы в пятницу'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='friday_time_to',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время окончания работы в пятницу'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='saturday_time_from',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время начала работы в субботу'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='saturday_time_to',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время окончания работы в субботу'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='sunday_time_from',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время начала работы в воскресенье'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='sunday_time_to',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время окончания работы в воскресенье'),
        ),
    ]
