# Generated by Django 4.0.3 on 2022-06-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0050_workinghours_friday_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagecond',
            name='pallet_handling_cost',
            field=models.FloatField(default=0, verbose_name='Стоимость приемки/отгрузки палет (с НДС)'),
        ),
        migrations.AlterField(
            model_name='storagecond',
            name='pallet_storage_cost',
            field=models.FloatField(default=0, verbose_name='Стоимость хранения палет (с НДС)'),
        ),
    ]
