# Generated by Django 4.0.3 on 2022-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0051_alter_storagecond_pallet_handling_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявки складу', 'verbose_name_plural': 'Заявки складу'},
        ),
        migrations.AlterModelOptions(
            name='surveyresults',
            options={'verbose_name': 'Запросы', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
