# Generated by Django 4.0.3 on 2022-06-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0052_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresults',
            name='long_term_commitment',
            field=models.BooleanField(default=False),
        ),
    ]
