# Generated by Django 4.0.3 on 2022-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0053_surveyresults_long_term_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresults',
            name='leveling_platform',
            field=models.BooleanField(default=False, verbose_name='Оборудование для выравнивания'),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='railways',
            field=models.BooleanField(default=False, verbose_name='Ж/д пути'),
        ),
    ]
